'use strict';

// Словарь интерфейса. Механика рядом, в i18n.js.
//
// Ключи собраны по экранам, а не по алфавиту целиком: правят их экранами,
// и строка, стоящая рядом со своими соседками, реже расходится с ними по
// тону. Значение массивом это формы числа: у русского их три, у английского
// две, выбирает их i18n.js, а не место вызова.
//
// Сюда не попадают и не должны попадать имена тегов, групп, файлов и путей.
// Это данные человека: заведённое по-русски остаётся русским, на каком бы
// языке он потом ни смотрел программу.

const STRINGS = {

  ru: {
    // карточка файла
    "card.away": "уехал",
    "card.movedAway": "Уехал из хранилища: {path}",

    // cat
    "cat.del.body": "Файлы остаются на диске и в библиотеке, их теги сохраняются. Пропадёт только связь: {items} лежать в этом каталоге.",
    "cat.del.count": ["{n} объект перестанет", "{n} объекта перестанут", "{n} объектов перестанут"],
    "cat.del.ok": "Удалить связь",
    "cat.del.title": "Удалить каталог «{name}»?",

    // общее для экранов
    "common.cancel": "Отмена",
    "common.cmd.delete": "Удалить",
    "common.cmd.details": "Сведения",
    "common.cmd.details.hint": "Панель сведений",
    "common.cmd.open": "Открыть",
    "common.cmd.rename": "Переименовать",
    "common.cmd.tags": "Настроить теги",
    "common.cmd.tile.large": "Крупные плитки",
    "common.cmd.tile.medium": "Средние плитки",
    "common.cmd.tile.small": "Мелкие плитки",
    "common.done": "Готово",
    "common.drop.zone": "Отпусти, заберу в разбор",
    "common.pick.addTag": "Добавить тег в отбор",
    "common.pick.mode.all": "И",
    "common.pick.mode.all.hint": "Файл должен иметь все выбранные теги",
    "common.pick.mode.any": "ИЛИ",
    "common.pick.mode.any.hint": "Файлу хватит любого из выбранных тегов",
    "common.pick.reset": "Сбросить отбор",
    "common.pick.search": "имя файла",
    "common.tag.new": "новый тег…",
    "common.tagNotFound": "Такого тега нет",
    "common.tagpick.search": "тег…",

    // удаление
    "del.body": "Уйдёт в корзину Windows, насовсем не стирается. Достанешь обратно, и файл вернётся вместе со всеми тегами.",
    "del.many.title": ["Удалить {n} файл?", "Удалить {n} файла?", "Удалить {n} файлов?"],
    "del.one.title": "Удалить «{name}»?",

    // приём
    "inbox.bar.untagged": ["{n} файл без тегов", "{n} файла без тегов", "{n} файлов без тегов"],
    "inbox.empty.body": "Папка «Inbox» пуста, всё разложено. Сохраняй туда что угодно, разберёшь потом одной пачкой.",
    "inbox.empty.title": "Разбирать нечего",
    "inbox.noMatch.body": ["В приёме {n} файл, но он не совпал. Сбрось отбор, чтобы увидеть всё.", "В приёме {n} файла, но ни один не совпал. Сбрось отбор, чтобы увидеть всё.", "В приёме {n} файлов, но ни один не совпал. Сбрось отбор, чтобы увидеть всё."],
    "inbox.noMatch.title": "Под отбор ничего не подошло",
    "inbox.pending": ["{n} файл ждёт", "{n} файла ждут", "{n} файлов ждут"],
    "inbox.scope.root": "Приём",
    "inbox.side.hint": "Выдели файлы, чтобы вешать теги",
    "inbox.side.selected": ["Выделено: {n} файл", "Выделено: {n} файла", "Выделено: {n} файлов"],
    "inbox.stats.files": "{n} в каталоге",

    // панель сведений
    "info.empty": "Ничего не выделено.",
    "info.emptyHint": "Выбери файл, и здесь будет всё, что о нём известно.",
    "info.formats": "Форматы",
    "info.inside": "Внутри",
    "info.items": ["{n} объект", "{n} объекта", "{n} объектов"],
    "info.modified": "Изменён",
    "info.movedAway": "Уехал из хранилища: {path}",
    "info.noTags": "Тегов нет",
    "info.size": "Размер",
    "info.tags": "Теги",
    "info.type": "Тип",
    "info.type.catalog": "Каталог",
    "info.type.noExt": "без расширения",

    // библиотека
    "lib.date.any": "Любая дата",
    "lib.date.created": "Создан",
    "lib.date.dash": "до",
    "lib.date.from": "с этой даты",
    "lib.date.group": "Дата",
    "lib.date.modified": "Изменён",
    "lib.date.to": "по эту дату",
    "lib.empty.body": "Файлы появятся здесь, когда разложишь то, что лежит в приёме.",
    "lib.empty.hintDates": "Раздвинь диапазон дат, сними лишний тег или переключи И на ИЛИ.",
    "lib.empty.hintTags": "Сними лишний тег или переключи И на ИЛИ, тогда хватит любого из выбранных.",
    "lib.empty.noMatch.title": "Ничего не нашлось",
    "lib.empty.title": "В библиотеке пусто",
    "lib.more": "Показать ещё {n}",
    "lib.panel.catalog": "Каталог",
    "lib.saved.del": "Удалить отбор",
    "lib.saved.title": "Сохранённые отборы",
    "lib.scope.goto": "Перейти в «{name}»",
    "lib.scope.root": "Библиотека",
    "lib.scope.up": "Выйти в библиотеку",
    "lib.status.items": ["Элементов: {n}", "Элементов: {n}", "Элементов: {n}"],
    "lib.status.selected": ["Выбран {n} элемент", "Выбрано {n} элемента", "Выбрано {n} элементов"],

    // библиотека
    "library.title": "Tanba, библиотека",

    // меню по правой кнопке
    "menu.deleteCatalog": "Удалить каталог",
    "menu.reveal": "Показать в проводнике",
    "menu.toCatalog": "В каталог",

    // modal
    "modal.pick.none": "Ничего не нашлось",
    "modal.pick.search": "поиск…",

    // вкладки
    "nav.library": "Библиотека",
    "nav.settings": "Настройки",
    "nav.tags": "Теги",
    "nav.triage": "Разбор",

    // переименование
    "rename.body": "Расширение остаётся прежним, менять его вручную не нужно.",

    // строка отбора
    "scope.removeFormat": "Убрать формат",
    "scope.removeTag": "Убрать тег",

    // настройки
    "set.root.pending": ["В приёме {n} файл", "В приёме {n} файла", "В приёме {n} файлов"],
    "set.root.scanning": "Считаю, что лежит в приёме",
    "set.startup.off": "Автозапуск выключен",
    "set.startup.on": "Tanba будет запускаться вместе с Windows",
    "set.up.available": "Есть версия {ver}",
    "set.up.checking": "Смотрю…",
    "set.up.failed.body": "Программа так и не отозвалась. Закрой окно и запусти Tanba заново.",
    "set.up.failed.title": "Обновление не установилось",
    "set.up.installed": "Установленная копия",
    "set.up.installing": "Устанавливаю, окно сейчас закроется и откроется заново",
    "set.up.never": "Ещё не проверяли",
    "set.up.noRepo": "репозиторий не задан при сборке",
    "set.up.noSource": "Источник обновлений не указан",
    "set.up.portable": "Запущена не из установленной копии, обновление недоступно",
    "set.up.upToDate": "Последняя проверка: {when}. Установлена самая свежая.",
    "set.up.updating.body": "Окно откроется заново само.",
    "set.up.updating.title": "Обновляюсь",
    "set.when.onDate": "{date} в {time}",
    "set.when.today": "сегодня в {time}",
    "set.when.yesterday": "вчера в {time}",

    // настройки
    "settings.look.heading": "Оформление",
    "settings.look.lang": "Язык",
    "settings.look.lang.note": "Меняется сразу, на всех экранах и у значка в трее.",
    "settings.look.theme": "Тема",
    "settings.look.theme.dark": "Тёмная",
    "settings.look.theme.light": "Светлая",
    "settings.look.theme.note": "Запоминается и держится на всех экранах.",
    "settings.startup.heading": "Запуск",
    "settings.startup.label": "Запускать вместе с Windows",
    "settings.startup.note": "Программа поднимается значком в трее и считает, сколько файлов ждёт разбора. Окно при этом не открывается.",
    "settings.storage.again": "Настроить заново",
    "settings.storage.again.body": "Мастер откроется на выбранном сейчас месте. Можно ничего не менять и просто закрыть его: файлы и теги останутся как есть.",
    "settings.storage.again.do": "Открыть мастер",
    "settings.storage.again.note": "Откроет мастер первого запуска: можно посмотреть его или выбрать другое место для архива. Программа перезапустится, файлы и теги останутся на месте.",
    "settings.storage.again.ok": "Перезапустить",
    "settings.storage.again.title": "Открыть мастер настройки?",
    "settings.storage.again.wait": "Перезапускаюсь",
    "settings.storage.again.waitNote": "Сейчас откроется мастер настройки.",
    "settings.storage.heading": "Хранилище",
    "settings.title": "Tanba, настройки",
    "settings.update.apply": "Обновить и перезапустить",
    "settings.update.check": "Проверить",
    "settings.update.checking": "Проверяю…",
    "settings.update.heading": "Обновление",
    "settings.update.version": "Версия",

    // первый запуск
    "setup.done.lead": "Сохраняй всё в «Inbox», разберёшь потом одной пачкой.",
    "setup.done.title": "Всё готово",
    "setup.fail.back": "Назад к выбору",
    "setup.fail.title": "Не получилось",
    "setup.lang.sub": "Его можно поменять потом в настройках.",
    "setup.lang.title": "Выбери язык",
    "setup.launch.autostart": "Запускать вместе с Windows",
    "setup.launch.shortcut": "Ярлык на рабочем столе",
    "setup.launch.sub": "Обе настройки можно поменять потом.",
    "setup.launch.title": "Как запускать",
    "setup.nav.back": "Назад",
    "setup.nav.connect": "Подключиться",
    "setup.nav.next": "Далее",
    "setup.nav.open": "Открыть Tanba",
    "setup.nav.prepare": "Готовить",
    "setup.nav.start": "Начать",
    "setup.nav.working": "Идёт подготовка",
    "setup.place.browse": "Обзор",
    "setup.place.placeholder": "D:\\Архив",
    "setup.place.sub": "Файлы остаются на диске. Tanba создаст рядом служебные папки и базу с тегами.",
    "setup.place.sub.tanba": "Нашёлся прежний каталог. Подключусь к нему, ничего не перезаписывая.",
    "setup.place.title": "Где держать архив",
    "setup.place.willmake": "Что появится в этой папке",
    "setup.plural.files": ["{n} файл", "{n} файла", "{n} файлов"],
    "setup.prog.counted": "{task}, {done} из {total}",
    "setup.prog.starting": "Начинаю",
    "setup.step.counter": "Шаг {n} из {total}, {name}",
    "setup.step.lang": "Язык",
    "setup.step.launch": "Как запускать",
    "setup.step.place": "Где держать архив",
    "setup.step.welcome": "Приветствие",
    "setup.step.work": "Готовлю",
    "setup.task.db": "Завожу базу",
    "setup.task.dirs": "Создаю папки",
    "setup.task.scan": "Смотрю, что уже лежит в архиве",
    "setup.verdict.created": "создан {date}",
    "setup.verdict.empty": "Заведу здесь всё с нуля",
    "setup.verdict.foreign": "Папка не пуста, свои папки создам рядом",
    "setup.verdict.gone": "Прежний путь недоступен, подключи диск или выбери другое место",
    "setup.verdict.items": "{n} внутри",
    "setup.verdict.tanba": "Каталог на {files}, подключусь к нему",
    "setup.welcome.lead": "Каталог файлов, который заменяет папки тегами. Настройка займёт минуту.",
    "setup.welcome.version": "версия {v}",
    "setup.work.failstart": "Не вышло начать.",
    "setup.work.sub": "Создаю служебные папки и смотрю, что уже лежит в архиве.",
    "setup.work.sub.adopt": "Папки и база уже есть, смотрю, что в них.",
    "setup.work.title": "Готовлю каталог",
    "setup.work.title.adopt": "Подключаюсь к каталогу",

    // теги
    "tag.group.single": "один тег",

    // теги
    "tags.del.body": ["Он стоит на {n} файле. Файлы останутся на диске и в библиотеке, пропадёт только эта пометка.", "Он стоит на {n} файлах. Файлы останутся на диске и в библиотеке, пропадёт только эта пометка.", "Он стоит на {n} файлах. Файлы останутся на диске и в библиотеке, пропадёт только эта пометка."],
    "tags.del.tip": "Удалить тег",
    "tags.del.title": "Удалить тег «{name}»?",
    "tags.delGroup.body": ["В ней {n} тег, расставленный {marks}. Файлы останутся на месте, пропадут только пометки.", "В ней {n} тега, расставленных {marks}. Файлы останутся на месте, пропадут только пометки.", "В ней {n} тегов, расставленных {marks}. Файлы останутся на месте, пропадут только пометки."],
    "tags.delGroup.marks": ["{n} раз", "{n} раза", "{n} раз"],
    "tags.delGroup.title": "Удалить группу «{name}» целиком?",
    "tags.flag.multi": "несколько тегов",
    "tags.flag.multi.tip": "Можно ли повесить на файл несколько тегов этой группы",
    "tags.flag.required": "обязательная",
    "tags.flag.required.tip": "Файл без тега из этой группы считается неразмеченным",
    "tags.group.del": "Удалить группу",
    "tags.group.new.hint": "Enter создаёт группу",
    "tags.group.new.placeholder": "новая группа…",
    "tags.merge.body": "Файлы этого тега получат выбранный, а сам он исчезнет.",
    "tags.merge.ok": "Объединить",
    "tags.merge.tip": "Объединить с другим тегом",
    "tags.merge.title": "Объединить «{name}» с другим тегом",
    "tags.mergeExists.body": "Объединить их? Все файлы, помеченные этим тегом, получат существующий, а лишний исчезнет.",
    "tags.mergeExists.title": "Тег «{name}» уже есть",
    "tags.none.note": "Завести теги",
    "tags.none.title": "Тегов пока нет",
    "tags.search": "имя тега",
    "tags.status.found": ["Нашлось {n} тег из {total}", "Нашлось {n} тега из {total}", "Нашлось {n} тегов из {total}"],
    "tags.status.groups": ["{n} группа", "{n} группы", "{n} групп"],
    "tags.status.tags": ["{n} тег", "{n} тега", "{n} тегов"],
    "tags.title": "Tanba, теги",

    // окно тегов
    "tagsdlg.body": "Выделено: {sel}. Промежуточная галочка означает, что тег стоит не у всех.",
    "tagsdlg.count": ["{n} объект", "{n} объекта", "{n} объектов"],
    "tagsdlg.title": "Теги",

    // сообщения
    "toast.actionFailed": "Не вышло: {error}",
    "toast.andMore": "и ещё {n}",
    "toast.catalogDeleted": "Каталог удалён, файлы на месте",
    "toast.catalogPickerSoon": "Выбор каталога делаю следующим",
    "toast.deleteFailed": "Не удалилось: {error}",
    "toast.deleted": "Удалено в корзину: {n}",
    "toast.dropNotYet": "Пока клади файлы в папку «Inbox», приём перетаскиванием на подходе",
    "toast.errors": "Ошибки: {list}",
    "toast.filed": "Разложено: {n}",
    "toast.filed.merged": "дубликатов слито: {n}",
    "toast.filedUntagged": "Отложено без тегов: {n}, ищи в «Неразобранном»",
    "toast.filterFailed": "Не удалось получить отбор: {error}",
    "toast.groupCreated": "Группа создана",
    "toast.groupDeleted": "Группа удалена",
    "toast.merged": ["Объединено с «{name}», перенесено: {n}", "Объединено с «{name}», перенесено: {n}", "Объединено с «{name}», перенесено: {n}"],
    "toast.mergedMarks": ["Объединено, перенесено расстановок: {n}", "Объединено, перенесено расстановок: {n}", "Объединено, перенесено расстановок: {n}"],
    "toast.nothingToMerge": "Объединять не с чем",
    "toast.openFailed": "Не открылось: {error}",
    "toast.openFailedShort": "Не открылось",
    "toast.renamed": "Переименовано",
    "toast.tagDeleted": "Тег удалён",

    // разбор
    "triage.file": "Разложить",
    "triage.later": "Отложить",
    "triage.later.hint": "Убрать из приёма без тегов, попадут в «Неразобранное»",
    "triage.rescan": "Пересканировать приём",
    "triage.title": "Tanba, разбор",

    // единицы
    "units.b": "Б",
    "units.gb": "ГБ",
    "units.kb": "КБ",
    "units.mb": "МБ",
    "units.tb": "ТБ",

    // кнопки окна
    "win.close": "Закрыть",
    "win.maximize": "Развернуть",
    "win.minimize": "Свернуть",
    "win.restore": "Вернуть прежний размер",
  },

  en: {
    // карточка файла
    "card.away": "moved",
    "card.movedAway": "Moved out of storage: {path}",

    // cat
    "cat.del.body": "The files stay on disk and in the library, and they keep their tags. Only the link goes: {items} be in this catalog.",
    "cat.del.count": ["{n} item will no longer", "{n} items will no longer"],
    "cat.del.ok": "Remove link",
    "cat.del.title": "Delete catalog “{name}”?",

    // общее для экранов
    "common.cancel": "Cancel",
    "common.cmd.delete": "Delete",
    "common.cmd.details": "Details",
    "common.cmd.details.hint": "Details pane",
    "common.cmd.open": "Open",
    "common.cmd.rename": "Rename",
    "common.cmd.tags": "Edit tags",
    "common.cmd.tile.large": "Large tiles",
    "common.cmd.tile.medium": "Medium tiles",
    "common.cmd.tile.small": "Small tiles",
    "common.done": "Done",
    "common.drop.zone": "Drop files here for triage",
    "common.pick.addTag": "Add a tag to the filter",
    "common.pick.mode.all": "All",
    "common.pick.mode.all.hint": "The file must have every selected tag",
    "common.pick.mode.any": "Any",
    "common.pick.mode.any.hint": "Any one of the selected tags is enough",
    "common.pick.reset": "Clear filters",
    "common.pick.search": "file name",
    "common.tag.new": "new tag…",
    "common.tagNotFound": "No such tag",
    "common.tagpick.search": "tag…",

    // удаление
    "del.body": "It goes to the Windows Recycle Bin, nothing is erased for good. Restore it and the file comes back with all its tags.",
    "del.many.title": ["Delete {n} file?", "Delete {n} files?"],
    "del.one.title": "Delete “{name}”?",

    // приём
    "inbox.bar.untagged": ["{n} file without tags", "{n} files without tags"],
    "inbox.empty.body": "The Inbox folder is empty, everything is sorted. Save anything there and go through it later in one batch.",
    "inbox.empty.title": "Nothing to sort",
    "inbox.noMatch.body": ["There is {n} file in the inbox, but it does not match. Clear the filters to see everything.", "There are {n} files in the inbox, but none of them match. Clear the filters to see everything."],
    "inbox.noMatch.title": "Nothing matches the filter",
    "inbox.pending": ["{n} file waiting", "{n} files waiting"],
    "inbox.scope.root": "Inbox",
    "inbox.side.hint": "Select files to tag them",
    "inbox.side.selected": ["{n} file selected", "{n} files selected"],
    "inbox.stats.files": "{n} in the catalog",

    // панель сведений
    "info.empty": "Nothing selected.",
    "info.emptyHint": "Pick a file and everything known about it shows up here.",
    "info.formats": "Formats",
    "info.inside": "Inside",
    "info.items": ["{n} item", "{n} items"],
    "info.modified": "Modified",
    "info.movedAway": "Moved out of storage: {path}",
    "info.noTags": "No tags",
    "info.size": "Size",
    "info.tags": "Tags",
    "info.type": "Type",
    "info.type.catalog": "Catalog",
    "info.type.noExt": "no extension",

    // библиотека
    "lib.date.any": "Any date",
    "lib.date.created": "Created",
    "lib.date.dash": "to",
    "lib.date.from": "from this date",
    "lib.date.group": "Date",
    "lib.date.modified": "Modified",
    "lib.date.to": "to this date",
    "lib.empty.body": "Files show up here once you sort what is waiting in the inbox.",
    "lib.empty.hintDates": "Widen the date range, drop a tag, or switch All to Any.",
    "lib.empty.hintTags": "Drop a tag, or switch All to Any so any one of them is enough.",
    "lib.empty.noMatch.title": "Nothing found",
    "lib.empty.title": "The library is empty",
    "lib.more": "Show {n} more",
    "lib.panel.catalog": "Catalog",
    "lib.saved.del": "Delete filter",
    "lib.saved.title": "Saved filters",
    "lib.scope.goto": "Go to “{name}”",
    "lib.scope.root": "Library",
    "lib.scope.up": "Back to the library",
    "lib.status.items": ["{n} item", "{n} items"],
    "lib.status.selected": ["{n} item selected", "{n} items selected"],

    // библиотека
    "library.title": "Tanba, Library",

    // меню по правой кнопке
    "menu.deleteCatalog": "Delete catalog",
    "menu.reveal": "Show in File Explorer",
    "menu.toCatalog": "Add to catalog",

    // modal
    "modal.pick.none": "Nothing found",
    "modal.pick.search": "search…",

    // вкладки
    "nav.library": "Library",
    "nav.settings": "Settings",
    "nav.tags": "Tags",
    "nav.triage": "Triage",

    // переименование
    "rename.body": "The extension stays as it is, you don’t need to type it.",

    // строка отбора
    "scope.removeFormat": "Remove format",
    "scope.removeTag": "Remove tag",

    // настройки
    "set.root.pending": ["{n} file in the inbox", "{n} files in the inbox"],
    "set.root.scanning": "Counting what is in the inbox",
    "set.startup.off": "Startup is off",
    "set.startup.on": "Tanba will start with Windows",
    "set.up.available": "Version {ver} is available",
    "set.up.checking": "Checking…",
    "set.up.failed.body": "The app never answered. Close this window and start Tanba again.",
    "set.up.failed.title": "The update did not install",
    "set.up.installed": "Installed copy",
    "set.up.installing": "Installing, the window will close and open again",
    "set.up.never": "Not checked yet",
    "set.up.noRepo": "repository was not set at build time",
    "set.up.noSource": "No update source is set",
    "set.up.portable": "Not running from an installed copy, updating is unavailable",
    "set.up.upToDate": "Last checked {when}. You have the newest version.",
    "set.up.updating.body": "The window will open again on its own.",
    "set.up.updating.title": "Updating",
    "set.when.onDate": "{date} at {time}",
    "set.when.today": "today at {time}",
    "set.when.yesterday": "yesterday at {time}",

    // настройки
    "settings.look.heading": "Appearance",
    "settings.look.lang": "Language",
    "settings.look.lang.note": "Applies right away, on every screen and in the tray icon.",
    "settings.look.theme": "Theme",
    "settings.look.theme.dark": "Dark",
    "settings.look.theme.light": "Light",
    "settings.look.theme.note": "Remembered and used on every screen.",
    "settings.startup.heading": "Startup",
    "settings.startup.label": "Start with Windows",
    "settings.startup.note": "Tanba starts as a tray icon and keeps count of the files waiting for triage. The window stays closed.",
    "settings.storage.again": "Set up again",
    "settings.storage.again.body": "The wizard opens on the folder you use now. You can change nothing and simply close it: files and tags stay as they are.",
    "settings.storage.again.do": "Open the wizard",
    "settings.storage.again.note": "Opens the first-run wizard: look through it, or pick a different place for the archive. Tanba restarts; files and tags stay where they are.",
    "settings.storage.again.ok": "Restart",
    "settings.storage.again.title": "Open the setup wizard?",
    "settings.storage.again.wait": "Restarting",
    "settings.storage.again.waitNote": "The setup wizard is about to open.",
    "settings.storage.heading": "Storage",
    "settings.title": "Tanba, Settings",
    "settings.update.apply": "Update and restart",
    "settings.update.check": "Check",
    "settings.update.checking": "Checking…",
    "settings.update.heading": "Updates",
    "settings.update.version": "Version",

    // первый запуск
    "setup.done.lead": "Save everything to Inbox and sort it later in one go.",
    "setup.done.title": "All set",
    "setup.fail.back": "Pick another place",
    "setup.fail.title": "It did not work",
    "setup.lang.sub": "You can change it later in settings.",
    "setup.lang.title": "Choose your language",
    "setup.launch.autostart": "Start with Windows",
    "setup.launch.shortcut": "Desktop shortcut",
    "setup.launch.sub": "Both settings can be changed later.",
    "setup.launch.title": "How to launch",
    "setup.nav.back": "Back",
    "setup.nav.connect": "Connect",
    "setup.nav.next": "Next",
    "setup.nav.open": "Open Tanba",
    "setup.nav.prepare": "Prepare",
    "setup.nav.start": "Start",
    "setup.nav.working": "Preparing…",
    "setup.place.browse": "Browse",
    "setup.place.placeholder": "D:\\Archive",
    "setup.place.sub": "Your files stay on disk. Tanba adds its own folders and a tag database next to them.",
    "setup.place.sub.tanba": "Found an existing catalog. I will connect to it without overwriting anything.",
    "setup.place.title": "Where to keep the archive",
    "setup.place.willmake": "What will appear in this folder",
    "setup.plural.files": ["{n} file", "{n} files"],
    "setup.prog.counted": "{task}, {done} of {total}",
    "setup.prog.starting": "Starting",
    "setup.step.counter": "Step {n} of {total}, {name}",
    "setup.step.lang": "Language",
    "setup.step.launch": "How to launch",
    "setup.step.place": "Where to keep the archive",
    "setup.step.welcome": "Welcome",
    "setup.step.work": "Preparing",
    "setup.task.db": "Creating the database",
    "setup.task.dirs": "Creating folders",
    "setup.task.scan": "Looking at what is already in the archive",
    "setup.verdict.created": "created {date}",
    "setup.verdict.empty": "I will set everything up here from scratch",
    "setup.verdict.foreign": "The folder is not empty, so my folders go alongside",
    "setup.verdict.gone": "The previous location is unavailable. Connect the drive or pick another place.",
    "setup.verdict.items": "{n} inside",
    "setup.verdict.tanba": "A catalog with {files}. I will connect to it.",
    "setup.welcome.lead": "A file catalog that replaces folders with tags. Setup takes a minute.",
    "setup.welcome.version": "version {v}",
    "setup.work.failstart": "Could not start.",
    "setup.work.sub": "Creating the working folders and looking at what is already in the archive.",
    "setup.work.sub.adopt": "The folders and database are already there, checking what is in them.",
    "setup.work.title": "Preparing the catalog",
    "setup.work.title.adopt": "Connecting to the catalog",

    // теги
    "tag.group.single": "one tag",

    // теги
    "tags.del.body": ["It is on {n} file. The file stays on disk and in the library. Only this mark goes away.", "It is on {n} files. The files stay on disk and in the library. Only this mark goes away."],
    "tags.del.tip": "Delete tag",
    "tags.del.title": "Delete tag “{name}”?",
    "tags.delGroup.body": ["It holds {n} tag, used {marks}. The files stay where they are. Only the marks go away.", "It holds {n} tags, used {marks}. The files stay where they are. Only the marks go away."],
    "tags.delGroup.marks": ["{n} time", "{n} times"],
    "tags.delGroup.title": "Delete the whole group “{name}”?",
    "tags.flag.multi": "multiple tags",
    "tags.flag.multi.tip": "Whether a file can carry more than one tag from this group",
    "tags.flag.required": "required",
    "tags.flag.required.tip": "A file with no tag from this group counts as untagged",
    "tags.group.del": "Delete group",
    "tags.group.new.hint": "Press Enter to create the group",
    "tags.group.new.placeholder": "new group…",
    "tags.merge.body": "Files with this tag get the one you pick, and this tag disappears.",
    "tags.merge.ok": "Merge",
    "tags.merge.tip": "Merge into another tag",
    "tags.merge.title": "Merge “{name}” into another tag",
    "tags.mergeExists.body": "Merge them? Every file marked with this tag gets the existing one, and the spare disappears.",
    "tags.mergeExists.title": "Tag “{name}” already exists",
    "tags.none.note": "Create tags",
    "tags.none.title": "No tags yet",
    "tags.search": "tag name",
    "tags.status.found": ["Found {n} tag out of {total}", "Found {n} tags out of {total}"],
    "tags.status.groups": ["{n} group", "{n} groups"],
    "tags.status.tags": ["{n} tag", "{n} tags"],
    "tags.title": "Tanba, tags",

    // окно тегов
    "tagsdlg.body": "{sel} selected. A dash instead of a check means the tag is only on some of them.",
    "tagsdlg.count": ["{n} item", "{n} items"],
    "tagsdlg.title": "Tags",

    // сообщения
    "toast.actionFailed": "Didn’t work: {error}",
    "toast.andMore": "and {n} more",
    "toast.catalogDeleted": "Catalog deleted, the files stayed put",
    "toast.catalogPickerSoon": "Catalog picking is next on my list",
    "toast.deleteFailed": "Could not delete: {error}",
    "toast.deleted": "Moved to the Recycle Bin: {n}",
    "toast.dropNotYet": "For now put files into the Inbox folder, drag and drop is on the way",
    "toast.errors": "Errors: {list}",
    "toast.filed": "Sorted: {n}",
    "toast.filed.merged": "duplicates merged: {n}",
    "toast.filedUntagged": "Set aside untagged: {n}, look in “Unsorted”",
    "toast.filterFailed": "Could not load the results: {error}",
    "toast.groupCreated": "Group created",
    "toast.groupDeleted": "Group deleted",
    "toast.merged": ["Merged into “{name}”, {n} mark moved", "Merged into “{name}”, {n} marks moved"],
    "toast.mergedMarks": ["Merged, {n} tag mark moved", "Merged, {n} tag marks moved"],
    "toast.nothingToMerge": "Nothing to merge with",
    "toast.openFailed": "Could not open: {error}",
    "toast.openFailedShort": "Could not open",
    "toast.renamed": "Renamed",
    "toast.tagDeleted": "Tag deleted",

    // разбор
    "triage.file": "Sort",
    "triage.later": "Set aside",
    "triage.later.hint": "Take them out of the inbox untagged, they land in “Unsorted”",
    "triage.rescan": "Rescan the inbox",
    "triage.title": "Tanba, triage",

    // единицы
    "units.b": "B",
    "units.gb": "GB",
    "units.kb": "KB",
    "units.mb": "MB",
    "units.tb": "TB",

    // кнопки окна
    "win.close": "Close",
    "win.maximize": "Maximize",
    "win.minimize": "Minimize",
    "win.restore": "Restore down",
  },
};
